baseURL = "https://osbook.club/"
languageCode = "zh-CN"
title = "「OSCAR·开源之书·共读」"
themesDir = "themes"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/logo-mobile.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/oscar-osbook-logo.png"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "OSPO Summit"

  [params.homepage_meta_tags]
    meta_description = "开源之书·共读"
    meta_og_title = "「OSCAR·开源之书·共读」"
    meta_og_type = "website"
    meta_og_url = "https://osbook.club"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = ""
    meta_twitter_card = "summary"
    meta_twitter_site = "@lijiangsheng1"
    meta_twitter_creator = "@lijiangsheng1"

[[menu.main]]
	name = "活动"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "「书单」"
    url = "/work/"
   weight = 2

[[menu.main]]
    name = "关于我们"
    url = "/about/"
    weight = 3

 [[menu.main]]
    name = "历史"
    url = "/history/"
    weight = 3

[[menu.main]]
    name = "联系"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"

